AllCops:
  TargetRubyVersion: 2.2

inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml

Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/trailblazer/option.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/**'

Style/ImplicitRuntimeError:
  Exclude:
    - 'lib/trailblazer/option.rb'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'test/option_test.rb'

Style/ClassAndModuleChildren:
  Enabled: false

# wants to use map instead of collect
Style/CollectionMethods:
  Enabled: false

# wants to use fail instea of raise
Style/SignalException:
  Enabled: false

# because in gemspec we say >= 2.0.0 wants to have 2.0 as target ruby version here but
# it's not supported anymore from rubocop
Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal
